version: '3.9'

services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_DB=hazard
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    container_name: hazard_base
    volumes:
      - /home/${USERNAME}/volumes/hazard/pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  hazard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hazard
    image: hazard:1.0
    ports:
      - 3001:3001
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
 